# Ajustar para maiúsculo #
a memoria em Carne Viva: a desolacao.

Alaide, uma pessoa perturbada.
Esta chovendo? SIM!
(Lembranca, uma rua deserta banhada por uma luz fraca) 
ATO I: O desepero.
	CENA I: 
		[ENTRA Alaide]
        # Alaide se encontra inquieta perambulando #
        ENQUANTO Esta chovendo, Alaide se pergunta:
            Alaide: ONDE ESTOU?
        os questionamentos de Alaide se ENCERRAM.
		[TODOS SAEM]