#line 2 "src/lex.yy.c"

#line 4 "src/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[597] =
    {   0,
        0,    0,   64,   62,   62,   51,   62,   55,   56,   25,
       57,   50,   52,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   53,   54,   62,   62,   61,    0,    0,    1,
       57,    5,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   17,   61,   61,    0,   61,   61,   14,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,    5,   61,
       61,   61,   61,   61,   11,   61,   61,   61,   61,   19,
       61,   61,   61,   61,   21,    0,   61,    4,    0,    0,
        0,   61,   61,   61,   61,   61,   61,   61,   61,   61,

        0,   61,   61,   61,   61,   16,   61,   61,   61,   61,
       61,   61,   61,   61,   13,    0,   61,   61,    9,   61,
       61,   61,   61,   22,   61,   12,   61,   61,   61,   61,
       61,   61,   61,   21,    0,   61,    0,    0,    0,   61,
       61,   61,   61,   61,   61,   58,   61,   61,    0,   61,
       61,   61,   61,    0,   61,   61,   61,   61,   61,   61,
       61,   61,   61,    0,    0,   61,   61,   61,   61,    0,
       45,   26,   61,   61,   61,   61,    0,   61,    0,    0,
        0,    0,    0,    0,   61,   40,   61,   61,   61,   61,
       61,    0,   61,   15,   24,   61,    0,   61,   61,   61,

       61,    0,   61,   61,   18,   18,   61,    0,    0,    0,
       59,   61,   61,    0,   61,   61,   23,   60,   20,   61,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       61,   61,    0,   61,    0,    0,   61,   24,   61,    0,
       47,    0,   61,    0,    0,    0,    0,    0,   18,   61,
        0,    0,    0,   61,   61,   44,   61,   61,   61,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       61,    0,    0,    0,   61,    0,   61,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   61,    0,
        0,    0,   61,   46,   61,    0,   61,    3,    0,    0,

        0,    0,    2,    0,    0,    0,    0,    0,    0,    0,
       61,    0,   28,    0,   39,    0,   61,    0,    0,    0,
        0,    0,    0,   30,    0,    0,    0,    0,   61,    0,
        0,    0,    0,    0,   43,   61,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   38,    0,    0,    0,    0,   32,    0,   61,
        0,    0,    0,    0,    0,    0,   61,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   61,   10,    0,    0,
        0,    0,    0,   61,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    6,    0,   27,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   48,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   29,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   42,    0,    0,
       31,    0,    0,    0,   41,    0,    0,    0,    0,    0,
        0,    0,    0,   33,    8,    0,    0,    0,    7,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   49,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   34,    0,    0,    0,    0,    0,    0,
       35,   36,    0,    0,   37,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    1,    1,    1,    1,    7,
        8,    1,    1,    9,    1,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,    1,
        1,    1,   13,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   23,   35,   23,   36,
       37,    1,   38,   39,    1,    1,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,    1,    1,    1,    1,    1,    1,    1,    1,
       40,    1,    1,    1,   41,    1,   42,   43,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   44,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   45,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[600] =
    {   0,
        0,   44,  906,  907,  887,  907,  898,  907,  907,  907,
      892,  907,  907,   44,   48,   43,   45,   47,   52,   49,
      898,   50,   46,   51,   72,   64,   73,   77,   79,   81,
       84,   88,  907,  907,  859,   71,  112,  121,  894,  907,
      888,   90,  894,   90,  103,  100,  893,  101,  129,  131,
      115,  892,  132,  133,  863,  136,  134,  890,  138,  142,
      143,  144,  149,  148,  147,  152,  154,  889,  907,   94,
      150,  157,  155,  167,  156,  158,  171,  178,  183,  888,
      184,  186,  188,  190,  860,  872,  191,  907,  871,  870,
      869,  193,  195,  200,  197,  198,  216,  217,  201,  204,

      853,  199,  220,  203,  881,  880,  205,  223,  224,  225,
      221,  222,  229,  235,  879,  225,  238,  240,  878,  241,
      242,  243,  247,  877,  249,  876,  251,  254,  256,  258,
      257,  260,  264,  907,  853,  874,  832,  850,  845,  870,
      265,  267,  269,  272,  273,  869,  270,  271,  855,  276,
      274,  289,  278,  854,  275,  294,  296,  283,  300,  304,
      305,  307,  310,  852,  851,  864,  308,  311,  312,  827,
      862,  861,  315,  313,  318,  319,  821,  320,  849,  329,
      821,  829,  843,  827,  323,  854,  321,  853,  338,   92,
      324,  829,  335,  851,  340,  342,  840,  336,  353,  354,

      358,  364,  369,  372,  355,  363,  371,  827,  819,  833,
      846,  366,  373,  822,  374,  375,  844,  843,  907,  376,
      842,    0,  373,  370,  375,  378,  831,  826,  829,  824,
      837,  377,  809,  402,  799,  834,  379,  833,  380,  805,
      831,  413,  830,  416,  800,  799,  417,  420,  827,  405,
      816,  825,  797,  410,  421,  907,  394,  419,  423,  447,
      817,  416,  814,  419,  440,  821,  798,  806,  789,  789,
      435,  802,  792,  787,  428,  785,  452,  812,  782,  797,
      780,  779,  431,  793,  777,  776,  775,  774,  432,  776,
      451,  773,  430,  800,  454,  762,  457,  907,  456,  458,

      464,  471,  792,  789,  467,  769,  754,  780,  793,  778,
      791,  790,  907,  775,  788,  773,  786,  767,  770,  769,
      492,  768,  495,  907,  496,  767,  500,  766,  456,  761,
      757,  754,  754,  489,  775,  503,  733,  496,  765,  497,
      498,  758,  734,  770,  757,  739,  757,  754,  765,  735,
      735,  742,  907,  761,  509,  744,  519,  907,  520,  522,
      736,  748,  731,  728,  734,  725,  433,  717,  744,  515,
      751,  740,  722,  725,  747,  723,  735,  730,  743,  728,
      712,  715,  723,  709,  721,  720,  508,  907,  719,  724,
      512,  710,  723,  731,  707,  715,  728,  713,  700,  713,

      724,  703,  700,  709,  691,  692,  689,  688,  706,  686,
      685,  676,  689,  699,  684,  688,  681,  907,  695,  907,
      684,  690,  704,  693,  679,  689,  690,  687,  675,  697,
      655,  681,  684,  673,  682,  681,  649,  907,  679,  670,
      664,  677,  671,  672,  665,  656,  669,  654,  665,  678,
      663,  650,  663,  634,  652,  652,  536,  651,  650,  633,
      645,  644,  644,  651,  642,  649,  652,  651,  638,  636,
      632,  647,  633,  641,  654,  541,  542,  546,  550,  630,
      626,  641,  624,  636,  636,  624,  634,  635,  644,  617,
      630,  615,  613,  611,  553,  609,  554,  557,  907,  611,

      610,  625,  611,  633,  622,  605,  617,  619,  618,  617,
      625,  596,  595,  609,  593,  592,  602,  609,  617,  597,
      595,  592,  596,  599,  611,  588,  598,  907,  609,  594,
      907,  593,  592,  582,  907,  587,  585,  602,  578,  573,
      599,  588,  583,  907,  907,  582,  568,  573,  907,  565,
      571,  568,  563,  588,  573,  563,  562,  559,  576,  907,
      549,  547,  551,  545,  550,  560,  555,  545,  552,  547,
      534,  537,  561,  535,  533,  545,  548,  546,  533,  523,
      505,  501,  499,  907,  510,  497,  500,  461,  460,  443,
      907,  907,  412,  307,  907,  907,  586,  161,  589

    } ;

static const flex_int16_t yy_def[600] =
    {   0,
      596,    1,  596,  596,  596,  596,  597,  596,  596,  596,
      596,  596,  596,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  596,  596,  596,  596,  598,  596,  597,  596,
      596,  596,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  596,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  596,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  596,  596,  598,  596,  596,  596,
      596,  598,  598,  598,  598,  598,  598,  598,  598,  598,

      596,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  596,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  596,  596,  598,  596,  596,  596,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  596,  598,
      598,  598,  598,  596,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  596,  596,  598,  598,  598,  598,  596,
      598,  598,  598,  598,  598,  598,  596,  598,  596,  596,
      596,  596,  596,  596,  598,  598,  598,  598,  598,  598,
      598,  596,  598,  598,  598,  598,  596,  598,  598,  598,

      598,  596,  598,  598,  598,  598,  598,  596,  596,  596,
      598,  598,  598,  596,  598,  598,  598,  598,  596,  598,
      596,  599,  596,  596,  596,  596,  596,  596,  596,  596,
      598,  598,  596,  598,  596,  596,  598,  598,  598,  596,
      598,  596,  598,  596,  596,  596,  596,  596,  598,  598,
      596,  596,  596,  598,  598,  596,  598,  598,  598,  596,
      599,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      598,  596,  596,  596,  598,  596,  598,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  598,  596,
      596,  596,  598,  598,  598,  596,  598,  596,  596,  596,

      596,  596,  599,  596,  596,  596,  596,  596,  596,  596,
      598,  596,  596,  596,  598,  596,  598,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  598,  596,
      596,  596,  596,  596,  598,  598,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  598,
      596,  596,  596,  596,  596,  596,  598,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  598,  596,  596,  596,
      596,  596,  596,  598,  596,  596,  596,  596,  596,  596,

      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,

      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,    0,  596,  596,  596

    } ;

static const flex_int16_t yy_nxt[953] =
    {   0,
        4,    5,    4,    5,    6,    7,    8,    9,   10,    6,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   21,   23,   24,   25,   26,   27,   21,   28,
       29,   30,   31,   32,   21,   21,   33,   34,    5,    4,
        4,    4,    4,    4,   35,   36,  596,   42,  596,  596,
       55,  596,  596,  596,  596,  596,   51,   37,   44,   45,
       46,   49,   52,   63,   64,   50,   53,   69,   65,   62,
       47,   54,   56,   59,   48,  596,  596,   57,   60,   58,
      596,   61,  596,   66,  596,   67,   86,  596,   38,   70,
       73,  596,   74,  596,   47,  596,   75,  596,   68,   71,

       76,   83,   72,  596,   69,   77,  596,   79,   81,   82,
      117,   78,  234,   80,   84,   42,   93,   89,  596,   92,
       90,   94,   88,   91,   88,   88,   44,   45,   46,   88,
       88,   95,  596,   88,  596,  596,  596,  596,   47,  596,
       98,  596,   48,   87,   96,  596,  596,  596,  100,  104,
      596,  596,  596,  596,   97,  596,  107,  596,  596,  596,
      596,  596,  105,   43,  102,   99,  118,  103,  109,  111,
      596,  106,  112,  110,  596,  114,  108,  113,  120,  119,
      115,  596,  126,  121,  123,  125,  596,   69,  124,  596,
      122,  596,  128,  596,  596,  127,  596,  130,  596,  129,

      596,  596,  596,  596,  596,  132,  596,  596,  596,  142,
      140,  145,  131,  133,  141,  143,   47,  136,  144,  596,
      596,  146,  148,  596,  596,  596,  596,  596,  596,  146,
      147,  150,  596,  151,  155,  153,  156,  157,  596,  158,
      164,  596,  146,  596,  596,  596,  596,  159,  161,  152,
      596,  160,  596,  162,  596,  166,  165,  596,  169,  596,
      596,   69,  171,  596,  172,  168,  163,  596,  596,  167,
      596,  124,  596,  596,  596,  596,  596,  596,  596,  596,
      186,  596,  175,  176,  173,  174,  596,  170,   47,  193,
      187,  198,  596,  190,  185,  178,  188,  596,  189,  596,

      194,  191,  195,  596,  177,  202,   52,  202,  596,  196,
      596,  596,  200,  596,  596,  596,  596,  199,  596,  146,
      205,  596,  596,  596,  596,  211,  596,  596,  212,  201,
      595,  207,  180,  206,  203,  204,  231,  220,  596,  596,
      222,  596,  216,  596,  213,  596,  215,  232,  217,  218,
      223,  146,  224,  241,  242,  239,  242,  596,  596,  244,
      237,  244,  225,  226,  238,  202,  596,  202,  235,  596,
      247,  243,  247,  248,  596,  248,  596,  596,  596,  596,
      596,  222,  596,  276,  222,  249,  222,  254,  258,  222,
      245,  223,  246,  249,  262,  257,  264,  596,  250,  223,

      259,  224,  271,  225,  255,  596,  263,  263,  596,  277,
      275,  225,  265,  596,  242,  211,  242,  244,  247,  244,
      247,  248,  596,  248,  596,  295,  596,  222,  289,  594,
      222,  596,  323,  596,  323,  596,  596,  304,  596,  293,
      262,  279,  281,  285,  282,  286,  287,  294,  288,  297,
      260,  222,  311,  329,  315,  596,  335,  596,  298,  596,
      596,  223,  394,  296,  331,  317,  332,  298,  299,  298,
      300,  360,  333,  225,  305,  298,  593,  338,  222,  299,
      301,  302,  298,  592,  591,  340,  336,  218,  223,  339,
      339,  301,  299,  355,  300,  355,  323,  357,  323,  357,

      225,  359,  365,  359,  301,  341,  596,  298,  298,  298,
      355,  596,  355,  590,  589,  366,  356,  369,  338,  299,
      357,  359,  357,  359,  367,  596,  298,  588,  587,  415,
      383,  301,  370,  416,  586,  387,  299,  477,  585,  477,
      385,  386,  495,  477,  495,  477,  584,  497,  301,  497,
      583,  498,  412,  498,  495,  497,  495,  497,  498,  582,
      498,  581,  580,  579,  578,  528,  577,  576,  575,  574,
      496,  573,  572,  571,  570,  569,  568,  567,  566,  565,
      564,  513,  515,  563,  562,  516,   39,   39,   39,  261,
      561,  261,  528,  560,  559,  558,  557,  556,  555,  554,

      553,  552,  551,  550,  549,  548,  547,  546,  545,  544,
      544,  531,  543,  542,  541,  528,  540,  539,  538,  537,
      536,  528,  535,  534,  533,  532,  531,  530,  529,  528,
      527,  526,  525,  524,  523,  522,  521,  520,  519,  518,
      517,  514,  512,  511,  510,  509,  508,  507,  506,  505,
      504,  503,  502,  501,  500,  438,  499,  494,  493,  492,
      491,  490,  489,  488,  487,  486,  485,  484,  483,  482,
      481,  438,  480,  479,  478,  476,  475,  474,  473,  472,
      471,  470,  469,  468,  467,  466,  465,  464,  463,  418,
      438,  462,  461,  460,  459,  458,  457,  456,  455,  454,

      453,  452,  451,  450,  449,  448,  447,  446,  445,  444,
      443,  442,  441,  440,  439,  438,  437,  436,  435,  434,
      433,  432,  431,  430,  429,  428,  427,  426,  425,  424,
      423,  422,  421,  420,  419,  418,  417,  414,  413,  411,
      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  298,  395,  393,  392,  391,
      390,  389,  388,  384,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  298,  368,  596,  364,
      363,  362,  361,  358,  358,  324,  354,  353,  352,  351,
      350,  596,  349,  348,  347,  346,  345,  344,  343,  342,

      222,  303,  337,  596,  334,  330,  328,  327,  326,  325,
      324,  322,  321,  320,  319,  318,  316,  314,  313,  312,
      310,  309,  308,  307,  306,  222,  303,  292,  291,  290,
      596,  284,  283,  280,  596,  278,  596,  274,  273,  272,
      270,  269,  268,  267,  266,  260,  596,  596,  256,  596,
      253,  252,  251,  240,  596,  236,  233,  596,  230,  229,
      228,  227,  221,  219,  596,  596,  214,  210,  209,  208,
      197,  192,  596,  184,  183,  182,  181,  180,  179,  596,
      596,  596,  596,  596,  154,  149,  139,  138,  137,  135,
      134,  596,  116,  596,  101,  596,   69,  596,   41,   40,

       85,  596,   41,   40,   38,  596,    3,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596
    } ;

static const flex_int16_t yy_chk[953] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,   16,   14,   17,   23,
       18,   15,   20,   22,   24,   19,   16,    2,   14,   14,
       14,   15,   17,   23,   24,   15,   17,   26,   24,   22,
       14,   17,   18,   19,   14,   25,   27,   18,   19,   18,
       28,   20,   29,   24,   30,   25,   36,   31,   36,   26,
       28,   32,   29,   44,   26,  190,   29,   70,   25,   27,

       29,   32,   27,   46,   48,   29,   45,   30,   31,   31,
       70,   29,  190,   30,   32,   37,   45,   42,   51,   44,
       42,   46,   38,   42,   38,   38,   37,   37,   37,   38,
       38,   48,   49,   38,   50,   53,   54,   57,   37,   56,
       51,   59,   37,   37,   49,   60,   61,   62,   54,   57,
       65,   64,   63,   71,   50,   66,   61,   67,   73,   75,
       72,   76,   59,  598,   56,   53,   71,   56,   63,   64,
       74,   60,   65,   63,   77,   66,   62,   65,   72,   71,
       67,   78,   76,   72,   74,   75,   79,   81,   74,   82,
       73,   83,   78,   84,   87,   77,   92,   81,   93,   79,

       95,   96,  102,   94,   99,   84,  104,  100,  107,   93,
       92,   96,   83,   84,   92,   94,   82,   87,   95,   97,
       98,  100,   99,  103,  111,  112,  108,  109,  110,   97,
       98,  102,  113,  103,  107,  104,  108,  109,  114,  110,
      116,  117,   97,  118,  120,  121,  122,  111,  112,  103,
      123,  111,  125,  113,  127,  117,  116,  128,  121,  129,
      131,  130,  125,  132,  127,  120,  114,  133,  141,  118,
      142,  123,  143,  147,  148,  144,  145,  151,  155,  150,
      142,  153,  129,  131,  128,  128,  158,  122,  130,  150,
      143,  155,  152,  147,  141,  133,  144,  156,  145,  157,

      151,  148,  152,  159,  132,  160,  152,  160,  161,  153,
      162,  167,  158,  163,  168,  169,  174,  156,  173,  157,
      162,  175,  176,  178,  187,  167,  185,  191,  168,  159,
      594,  163,  180,  162,  161,  161,  185,  178,  193,  198,
      180,  189,  174,  195,  169,  196,  173,  187,  175,  176,
      180,  189,  180,  198,  199,  196,  199,  200,  205,  201,
      193,  201,  180,  180,  195,  202,  206,  202,  191,  212,
      203,  200,  203,  204,  207,  204,  213,  215,  216,  220,
      232,  224,  237,  239,  223,  205,  225,  212,  216,  226,
      202,  224,  202,  206,  223,  215,  225,  257,  207,  226,

      220,  226,  232,  224,  213,  234,  223,  223,  250,  239,
      237,  226,  226,  254,  242,  234,  242,  244,  247,  244,
      247,  248,  258,  248,  255,  257,  259,  262,  250,  593,
      264,  275,  283,  293,  283,  289,  367,  262,  271,  254,
      264,  242,  244,  247,  244,  247,  248,  255,  248,  259,
      260,  265,  271,  289,  275,  277,  293,  295,  260,  329,
      297,  265,  367,  258,  291,  277,  291,  299,  260,  300,
      260,  329,  291,  265,  265,  301,  590,  299,  305,  300,
      260,  260,  302,  589,  588,  301,  295,  297,  305,  299,
      299,  300,  302,  321,  302,  321,  323,  325,  323,  325,

      305,  327,  334,  327,  302,  302,  336,  338,  340,  341,
      355,  387,  355,  587,  586,  334,  323,  338,  340,  341,
      357,  359,  357,  359,  336,  360,  370,  585,  583,  391,
      355,  341,  341,  391,  582,  360,  370,  457,  581,  457,
      357,  359,  476,  477,  476,  477,  580,  478,  370,  478,
      579,  479,  387,  479,  495,  497,  495,  497,  498,  578,
      498,  577,  576,  575,  574,  573,  572,  571,  570,  569,
      477,  568,  567,  566,  565,  564,  563,  562,  561,  559,
      558,  495,  497,  557,  556,  498,  597,  597,  597,  599,
      555,  599,  554,  553,  552,  551,  550,  548,  547,  546,

      543,  542,  541,  540,  539,  538,  537,  536,  534,  533,
      532,  530,  529,  527,  526,  525,  524,  523,  522,  521,
      520,  519,  518,  517,  516,  515,  514,  513,  512,  511,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  496,  494,  493,  492,  491,  490,  489,  488,  487,
      486,  485,  484,  483,  482,  481,  480,  475,  474,  473,
      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  460,  459,  458,  456,  455,  454,  453,  452,
      451,  450,  449,  448,  447,  446,  445,  444,  443,  442,
      441,  440,  439,  437,  436,  435,  434,  433,  432,  431,

      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      419,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  390,  389,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  369,  368,  366,  365,  364,
      363,  362,  361,  356,  354,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  339,  337,  335,  333,
      332,  331,  330,  328,  326,  322,  320,  319,  318,  317,
      316,  315,  314,  312,  311,  310,  309,  308,  307,  306,

      304,  303,  296,  294,  292,  290,  288,  287,  286,  285,
      284,  282,  281,  280,  279,  278,  276,  274,  273,  272,
      270,  269,  268,  267,  266,  263,  261,  253,  252,  251,
      249,  246,  245,  243,  241,  240,  238,  236,  235,  233,
      231,  230,  229,  228,  227,  221,  218,  217,  214,  211,
      210,  209,  208,  197,  194,  192,  188,  186,  184,  183,
      182,  181,  179,  177,  172,  171,  170,  166,  165,  164,
      154,  149,  146,  140,  139,  138,  137,  136,  135,  126,
      124,  119,  115,  106,  105,  101,   91,   90,   89,   86,
       85,   80,   68,   58,   55,   52,   47,   43,   41,   39,

       35,   21,   11,    7,    5,    3,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer.l"
#line 2 "src/lexer.l"
    #include <stdio.h>
    #include <string.h> 
    #include "parser.tab.h"

    int DEBUG_LEX = 1;
    
    // Função auxiliar para converter números romanos para inteiros
    int romano_para_inteiro(const char *romano) {
        int valor = 0;
        while (*romano) {
            switch (*romano) {
                case 'M': valor += 1000; break;
                case 'D': valor += 500; break;
                case 'C':
                    if (*(romano + 1) == 'M') { valor += 900; romano++; }
                    else if (*(romano + 1) == 'D') { valor += 400; romano++; }
                    else valor += 100;
                    break;
                case 'L': valor += 50; break;
                case 'X':
                    if (*(romano + 1) == 'C') { valor += 90; romano++; }
                    else if (*(romano + 1) == 'L') { valor += 40; romano++; }
                    else valor += 10;
                    break;
                case 'V': valor += 5; break;
                case 'I':
                    if (*(romano + 1) == 'X') { valor += 9; romano++; }
                    else if (*(romano + 1) == 'V') { valor += 4; romano++; }
                    else valor += 1;
                    break;
            }
            romano++;
        }
        return valor;
    }
#line 885 "src/lex.yy.c"
#line 886 "src/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "src/lexer.l"

#line 1108 "src/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 597 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 907 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 39 "src/lexer.l"
{ /* comentário multilinha */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "src/lexer.l"
{
    char romano[16];
    sscanf(yytext, "ATO %15[^:]", romano);
    int numero = romano_para_inteiro(romano);
    if (DEBUG_LEX) printf("TOKEN: ATO (%s)\n", yytext);
    yylval.inteiro = numero;
    return ATO;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "src/lexer.l"
{
    char romano[16];
    sscanf(yytext, "CENA %15[^:]", romano);
    int numero = romano_para_inteiro(romano);
    if (DEBUG_LEX) printf("TOKEN: CENA (%s)\n", yytext);
    yylval.inteiro = numero;
    return CENA;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 58 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: E\n");
    yylval.texto = strdup(yytext);
    return E;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ARTIGO (%s)\n", yytext);
    yylval.texto = strdup(yytext);
    return ARTIGO;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 70 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ONDE_ESTAMOS\n");
    yylval.texto = strdup(yytext);
    return MOSTRAR_CENARIO;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 76 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ADICIONAR_CENARIO\n");
    yylval.texto = strdup(yytext);
    return ADICIONAR_CENARIO;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SUBSTITUIR_CENARIO\n");
    yylval.texto = strdup(yytext);
    return SUBSTITUIR_CENARIO;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 88 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: POR\n");
    yylval.texto = strdup(yytext);
    return POR;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: NO_CENARIO\n");
    yylval.texto = strdup(yytext);
    return NO_CENARIO;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SE\n");
    yylval.texto = strdup(yytext);
    return SE;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 106 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SIM\n");
    yylval.texto = strdup(yytext);
    return SIM;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: NAO\n");
    yylval.texto = strdup(yytext);
    return NAO;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 118 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: EU\n");
    yylval.texto = strdup(yytext);
    return EU;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 124 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENTAO\n");
    yylval.texto = strdup(yytext);
    return ENTAO;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 130 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FOR\n");
    yylval.texto = strdup(yytext);
    return FOR;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 136 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENTRE\n");
    yylval.texto = strdup(yytext);
    return ENTRE;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 141 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MESMO\n");
    yylval.texto = strdup(yytext);
    return MESMO;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 146 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: TU\n");
    yylval.texto = strdup(yytext);
    return TU;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 151 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: VOCE\n");
    yylval.texto = strdup(yytext);
    return VOCE;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 156 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: É\n");
    yylval.texto = strdup(yytext);
    return EH;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 161 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SAEM\n");
    yylval.texto = strdup(yytext);
    return SAEM;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 167 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: TODOS\n");
    yylval.texto = strdup(yytext);
    return TODOS;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 173 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENTRAM\n");
    yylval.texto = strdup(yytext);
    return ENTRAM;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 179 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: VIRGULA\n");
    return VIRGULA;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 183 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SOMA\n");
    yylval.texto = strdup(yytext);
    return SOMAR;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 189 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SUBTRAÇÃO\n");
    yylval.texto = strdup(yytext);
    return SUBTRAIR;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 195 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: DIVISÃO\n");
    yylval.texto = strdup(yytext);
    return DIVIDIR;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 201 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MULTIPLICAÇÃO\n");
    yylval.texto = strdup(yytext);
    return MULTIPLICAR;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 207 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MAIOR\n");
    yylval.texto = strdup(yytext);
    return MAIOR;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 213 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MAIOR_IGUAL\n");
    yylval.texto = strdup(yytext);
    return MAIOR_IGUAL;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 219 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MENOR\n");
    yylval.texto = strdup(yytext);
    return MENOR;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 225 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MENOR_IGUAL\n");
    yylval.texto = strdup(yytext);
    return MENOR_IGUAL;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 232 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MOSTRA_VALOR\n");
    yylval.texto = strdup(yytext);
    return MOSTRA_VALOR;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 238 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: IF_MOSTRA_VALOR\n");
    yylval.texto = strdup(yytext);
    return IF_MOSTRA_VALOR;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 244 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: LE_VALOR\n");
    yylval.texto = strdup(yytext);
    return LE_VALOR;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 250 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: IF_LE_VALOR\n");
    yylval.texto = strdup(yytext);
    return IF_LE_VALOR;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 256 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: IGUAL\n");
    yylval.texto = strdup(yytext);
    return IGUAL;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 262 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENQUANTO_COMECO\n");
    yylval.texto = strdup(yytext);
    return ENQUANTO_COMECO;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 268 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENQUANTO_FIM\n");
    yylval.texto = strdup(yytext);
    return ENQUANTO_FIM;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 274 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FINALIZACAO\n");
    yylval.texto = strdup(yytext);
    return FINALIZACAO;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 280 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENDIF\n");
    yylval.texto = strdup(yytext);
    return ENDIF;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 286 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FACA\n");
    yylval.texto = strdup(yytext);
    return FACA;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 292 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: DIVIDIR\n");
    yylval.texto = strdup(yytext);
    return DIVIDIR;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 298 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SERA\n");
    yylval.texto = strdup(yytext);
    return SERA;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 304 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MULTIPLICAR\n");
    yylval.texto = strdup(yytext);
    return MULTIPLICAR;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 310 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: GUARDE\n");
    yylval.texto = strdup(yytext);
    return GUARDE;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 316 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: INTERIOR\n");
    yylval.texto = strdup(yytext);
    return INTERIOR;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 322 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: LEMBRE\n");
    yylval.texto = strdup(yytext);
    return LEMBRE;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 328 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: INICIO\n");
    return INICIO;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 333 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FIM\n");
    return FIM;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 337 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: INTERROGACAO\n");
    return INTERROGACAO;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 342 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ABRE_COLCHETES\n");
    return ABRE_COLCHETES;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 347 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FECHA_COLCHETES\n");
    return FECHA_COLCHETES;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 352 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ABRE_PARENTESES\n");
    return ABRE_PARENTESES;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 357 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FECHA_PARENTESES\n");
    return FECHA_PARENTESES;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 362 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: NUMERO (%s)\n", yytext);
    yylval.texto = strdup(yytext);
    return NUMERO;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 368 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ADJETIVO_POSITIVO (%s)\n", yytext);
    yylval.texto = strdup(yytext);
    return ADJETIVO_POSITIVO;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 373 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ADJETIVO_NEGATIVO (%s)\n", yytext);
    yylval.texto = strdup(yytext);
    return ADJETIVO_NEGATIVO;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 378 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: VOLTAR CENÁRIO\n");
    yylval.texto = strdup(yytext);
    return VOLTAR_CENARIO;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 383 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: TOKEN (%s)\n", yytext);
    yylval.texto = strdup(yytext);
    return TOKEN;
}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 390 "src/lexer.l"
{ /* ignora tudo o resto */ }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 392 "src/lexer.l"
ECHO;
	YY_BREAK
#line 1721 "src/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 597 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 597 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 596);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 392 "src/lexer.l"



int yywrap() {
    return 1;
}
