#line 2 "src/lex.yy.c"

#line 4 "src/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[440] =
    {   0,
        0,    0,   54,   52,   52,   42,   52,   46,   47,   24,
       48,   41,   43,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   44,   45,   51,   51,   51,   51,   51,   52,   52,
       52,   51,    0,    0,    1,   48,    5,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   17,   51,   51,    0,
       51,   51,   14,   51,   51,   51,   51,    5,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       11,   51,   51,   51,   51,   19,   51,   51,   20,    0,
       51,    4,    0,    0,   51,   51,   51,   51,   51,   51,

       51,   51,   51,   51,    0,   51,   51,   51,   16,   51,
       51,   51,   51,   51,   51,   51,   13,    0,   51,   51,
        9,   51,   51,   51,   51,   51,   21,   12,   51,   51,
       51,   51,   51,   20,    0,   51,    0,    0,   51,   51,
       51,   51,   51,   49,   49,   51,   49,   51,   49,    0,
       51,   51,   51,   51,    0,   51,   51,   51,   51,   51,
       51,   51,    0,   51,   51,   51,   51,   51,    0,   21,
       25,   51,   51,   51,    0,   51,    0,    0,    0,    0,
        0,   36,   51,   51,   51,   51,   51,    0,   51,   15,
       23,   17,   51,    0,   51,   49,   51,    0,   51,   51,

       51,   18,   51,    0,    0,   50,   51,   49,   51,    0,
       51,   51,   22,   19,   18,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   51,    0,   49,   51,    0,    0,
       51,   23,   51,    0,    0,    0,    0,    0,    0,   18,
       18,   51,    0,    0,   51,   51,   39,   51,   51,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   51,    0,
       50,    0,    0,   51,    0,    0,    0,    0,    0,    0,
        0,   51,    0,    0,   40,   51,   51,    0,    3,    0,
        0,    0,    0,    2,    0,    0,    0,    0,    0,   51,
        0,   27,    0,   35,    0,    0,    0,    0,   29,    0,

        0,   51,    0,    0,   38,   51,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   33,
       30,   51,    0,    0,    0,    8,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   51,   10,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    6,   26,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       28,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   37,    0,    0,    0,
        0,    0,    0,    0,    7,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   31,    0,    0,   32,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    1,    1,    1,    1,    7,
        8,    1,    1,    9,    1,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,    1,
        1,    1,   13,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   23,   35,   23,   36,
       37,    1,   38,   39,    1,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   23,   23,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   23,   23,
       23,   60,    1,   61,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   62,    1,    1,    1,   63,    1,   64,   65,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       66,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   67,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[443] =
    {   0,
        0,   66,  992,  993,   51,  993,  985,  993,  993,  993,
      979,  993,  993,   66,   70,   71,   69,   68,   85,  985,
       72,   86,  102,  101,   74,  125,  130,  180,  123,  984,
      127,  993,  993,  147,  135,  144,  181,  178,  983,  922,
      129,  202,  244,  979,  993,  973,   84,  979,  174,  183,
      218,   82,  199,  188,  205,  238,  978,   98,  231,  924,
      246,  247,  976,  197,   99,  255,  256,  993,  257,  260,
      258,  263,  975,  266,  267,  265,  276,  281,  268,  302,
      974,  273,  310,  297,  314,  973,  283,  317,  295,  958,
      132,  993,  931,  930,  323,  330,  328,  168,  326,  335,

      338,  351,  332,  354,  915,  343,  349,  352,  968,  967,
      360,  377,  355,  357,  388,  333,  966,   55,  379,  373,
      965,  389,  392,  384,  390,  395,  964,  963,  401,  398,
      404,  408,  412,  993,  940,  961,  913,  908,  958,  421,
      417,  414,  418,  957,  956,  422,  955,  420,  954,  914,
      438,  432,  449,  415,  913,  446,  456,  444,   75,  473,
      454,  469,  156,  951,  478,  475,  462,  439,  892,  949,
      948,  481,  484,  488,  886,  496,  936,  523,  892,  905,
      454,  943,  494,  942,  511,  503,  423,  893,  505,  940,
      493,  939,  512,  902,  163,  937,  292,  530,  538,  551,

      533,  537,  526,  523,  542,  936,  558,  935,  557,  536,
      561,  562,  934,  993,  563,  933,    0,  563,  558,  559,
      579,  892,  895,  551,  573,  878,  929,  568,  870,  927,
      574,  926,  925,  872,  608,  614,  563,  618,  621,  923,
      922,  583,  586,  573,  607,  623,  993,  613,  569,  629,
      915,  616,  912,  618,  632,  872,  879,  602,  638,  877,
      916,  619,  863,  653,  616,  914,  616,  619,  621,  625,
      628,  665,  646,  647,  913,  222,  651,  853,  993,  673,
      669,  676,  688,  905,  902,  677,  846,  868,  907,  906,
      905,  993,  864,  903,  672,  858,  674,  675,  993,  676,

      684,  710,  684,  703,  901,  711,  837,  709,  891,  712,
      715,  839,  897,  717,  721,  858,  895,  696,  849,  993,
      993,  732,  711,  714,  707,  893,  834,  883,  735,  854,
      837,  714,  715,  852,  847,  886,  831,  693,  993,  718,
      875,  721,  883,  842,  723,  881,  835,  832,  740,  826,
      818,  727,  993,  993,  835,  875,  748,  752,  838,  835,
      744,  809,  808,  861,  825,  817,  758,  757,  867,  826,
      747,  803,  806,  815,  815,  765,  755,  806,  802,  770,
      808,  759,  806,  806,  760,  775,  842,  790,  774,  788,
      993,  802,  789,  834,  762,  794,  751,  779,  780,  771,

      695,  770,  775,  652,  515,  772,  993,  455,  781,  780,
      445,  445,  389,  744,  993,  238,  783,  263,  791,  217,
      791,  788,  159,  762,  800,  124,  803,  791,  164,  796,
      809,  814,  806,  797,  993,  816,  812,  993,  993,  861,
       90,  864
    } ;

static const flex_int16_t yy_def[443] =
    {   0,
      439,    1,  439,  439,  439,  439,  440,  439,  439,  439,
      439,  439,  439,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  439,  439,  441,  441,  441,  441,  441,  439,  439,
      439,  441,  439,  440,  439,  439,  439,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  439,
      441,  441,  441,  441,  441,  441,  441,  439,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  439,  439,
      441,  439,  439,  439,  441,  441,  441,  441,  441,  441,

      441,  441,  441,  441,  439,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  439,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  439,  439,  441,  439,  439,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  439,
      441,  441,  441,  441,  439,  441,  441,  441,  441,  441,
      441,  441,  439,  441,  441,  441,  441,  441,  439,  441,
      441,  441,  441,  441,  439,  441,  439,  439,  439,  439,
      439,  441,  441,  441,  441,  441,  441,  439,  441,  441,
      441,  441,  441,  439,  441,  441,  441,  439,  441,  441,

      441,  441,  441,  439,  439,  441,  441,  441,  441,  439,
      441,  441,  441,  439,  441,  439,  442,  439,  439,  439,
      439,  439,  439,  439,  441,  439,  441,  441,  439,  439,
      441,  441,  441,  439,  439,  439,  439,  439,  439,  441,
      441,  441,  439,  439,  441,  441,  439,  441,  441,  439,
      442,  439,  439,  439,  439,  439,  439,  439,  441,  439,
      441,  439,  439,  441,  439,  439,  439,  439,  439,  439,
      439,  441,  439,  439,  441,  441,  441,  439,  439,  439,
      439,  439,  439,  442,  439,  439,  439,  439,  439,  441,
      439,  439,  439,  441,  439,  439,  439,  439,  439,  439,

      439,  441,  439,  439,  441,  441,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  441,  439,  439,  439,  441,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  441,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,    0,  439,
      439,  439
    } ;

static const flex_int16_t yy_nxt[1061] =
    {   0,
        4,    5,    4,    5,    6,    7,    8,    9,   10,    6,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   21,   20,   22,   23,   24,   25,   26,   20,   27,
       28,   29,   30,   31,   20,   20,   32,   33,    5,   34,
       15,   16,   17,   35,   36,   20,   20,   21,   22,   37,
       24,   25,   38,   20,   27,   28,   29,   30,   31,   20,
       39,    4,    4,    4,    4,    4,   40,   41,   43,   47,
      163,   60,  439,  439,  439,  439,  198,   68,  198,   42,
       49,   50,   51,   53,   55,  439,   57,   54,  439,  439,
       58,   66,   48,   61,   43,   59,  163,   56,   62,   74,

       63,  439,  439,   67,   68,   68,   49,   50,   51,   53,
       55,   64,   57,   54,   72,   69,   58,   66,   61,   70,
       59,   52,   56,   62,   74,   63,  439,   73,  439,   67,
      439,  103,   65,  439,   71,  439,   64,   98,  439,   93,
       72,   69,   94,   79,   90,   70,   43,  439,  110,   85,
       68,   75,   73,   87,   76,   86,  103,   77,  136,   71,
       61,   49,   50,   51,  235,   62,  235,   63,  407,   79,
       64,  439,   43,  204,   85,  429,   75,  439,   87,   78,
       86,  439,   77,   68,   68,   61,  439,   49,   50,   51,
       62,  439,   63,   80,   69,   64,   96,   81,   70,  204,

      439,   82,  439,   95,   75,   47,   83,   76,  439,  426,
       77,  100,   84,   71,   99,  142,   49,   50,   51,   80,
       69,  439,   96,   81,   88,  439,  109,   82,   95,   75,
      101,   83,   76,   91,  439,   77,  100,   84,   71,   97,
       99,  439,   49,   50,   51,   92,  104,   92,   92,  439,
      439,  109,   92,   92,  102,  101,   92,   52,  439,  439,
      439,  439,  108,  439,  423,   97,  439,  407,  439,  439,
      439,  439,  104,  305,  106,  112,  439,  107,  113,  439,
      102,  116,  119,  120,  439,  114,  439,  111,  108,  117,
      115,  122,  123,  236,  420,  236,  121,  128,  132,  106,

      439,  112,  107,  125,  113,  439,  116,  122,  119,  120,
      114,  130,  111,  439,  117,  115,  122,  439,  123,  126,
      439,  121,  128,  127,  132,  134,  439,  125,  124,  439,
      131,  439,  122,  439,  129,  439,  439,  130,  439,  143,
      139,  439,  114,  141,  140,  126,  439,  115,  144,  127,
      134,  146,  439,  148,  439,  439,  131,  439,  439,  129,
      439,  145,  152,  439,  162,  143,  139,  114,  147,  141,
      140,  149,  133,  156,  144,  151,  439,  146,  153,  148,
      439,  158,  439,  160,  154,  159,  145,  439,  152,  162,
      157,  439,  439,  439,  147,  439,  164,  149,  439,  156,

      151,  439,  165,  153,  439,  166,  158,  439,  160,  154,
      159,  439,  161,  167,  171,  439,  157,  439,  439,  170,
      439,  439,  164,  439,  439,  439,  439,  165,  172,  173,
      174,  166,  418,  168,  182,  439,  161,  161,  183,  167,
      171,  439,  439,  185,  170,  186,  193,  439,  417,  439,
      187,  189,  439,  172,  173,  174,  169,  439,  190,  439,
      182,  176,  191,  184,  183,  439,  192,  201,  185,  195,
      186,  193,  439,  197,  175,  187,  439,  189,  439,  196,
      202,  439,  209,  190,  439,  224,  208,  439,  191,  229,
      203,  439,  192,  201,  195,  206,  439,  439,  197,  439,

      416,  413,  199,  200,  196,  202,  439,  207,  439,  201,
      224,  208,  211,  212,  439,  439,  203,  232,  213,  407,
      225,  206,  202,  228,  227,  233,  178,  199,  200,  439,
      231,  198,  207,  198,  217,  215,  439,  211,  212,  238,
      439,  238,  232,  213,  218,  225,  219,  202,  243,  228,
      227,  233,  239,  242,  239,  231,  220,  221,  237,  244,
      439,  439,  247,  240,  439,  439,  439,  241,  258,  217,
      217,  439,  439,  243,  217,  249,  439,  439,  242,  218,
      254,  261,  248,  237,  252,  244,  439,  247,  240,  245,
      217,  220,  241,  240,  258,  269,  253,  253,  259,  273,

      218,  249,  219,  274,  246,  264,  272,  261,  248,  235,
      439,  235,  220,  255,  245,  236,  439,  236,  240,  238,
      269,  238,  239,  259,  239,  273,  439,  217,  274,  217,
      264,  272,  250,  275,  289,  278,  267,  285,  299,  252,
      279,  439,  268,  217,  277,  292,  270,  295,  297,  271,
      280,  298,  281,  218,  439,  290,  439,  300,  275,  289,
      301,  267,  282,  283,  299,  220,  286,  268,  439,  277,
      292,  270,  295,  297,  271,  303,  298,  276,  304,  294,
      279,  290,  300,  306,  279,  301,  302,  279,  217,  318,
      280,  320,  299,  321,  308,  411,  439,  310,  218,  279,

      303,  321,  282,  304,  294,  323,  309,  309,  306,  280,
      220,  281,  302,  439,  439,  318,  324,  320,  299,  321,
      279,  282,  311,  279,  326,  322,  279,  321,  336,  325,
      328,  323,  332,  308,  333,  439,  280,  339,  340,  341,
      345,  346,  324,  408,  352,  338,  279,  354,  282,  329,
      326,  322,  357,  336,  325,  361,  280,  364,  332,  351,
      333,  367,  339,  340,  341,  345,  346,  368,  282,  352,
      371,  338,  354,  376,  377,  407,  380,  357,  385,  419,
      386,  361,  364,  389,  407,  391,  394,  367,  395,  398,
      405,  403,  406,  368,  409,  371,  410,  427,  412,  376,

      377,  380,  414,  419,  385,  386,  415,  421,  422,  389,
      391,  394,  424,  428,  395,  398,  403,  425,  406,  409,
      430,  427,  410,  412,  431,  432,  433,  434,  414,  435,
      436,  415,  421,  437,  422,  438,  404,  402,  424,  428,
      401,  400,  425,  399,  397,  396,  430,  393,  392,  431,
      432,  390,  433,  434,  435,  436,  388,  387,  384,  437,
      438,   44,   44,   44,  251,  383,  251,  382,  381,  379,
      378,  375,  374,  353,  373,  372,  370,  369,  366,  365,
      363,  362,  360,  359,  358,  356,  355,  353,  350,  349,
      348,  347,  344,  343,  279,  342,  439,  337,  335,  334,

      331,  330,  279,  327,  439,  319,  439,  317,  316,  315,
      314,  313,  312,  217,  284,  307,  439,  296,  293,  439,
      291,  288,  287,  217,  284,  439,  439,  266,  265,  439,
      263,  262,  439,  260,  257,  256,  250,  439,  439,  439,
      439,  234,  439,  439,  230,  226,  439,  223,  222,  216,
      214,  439,  439,  210,  205,  194,  188,  439,  439,  439,
      439,  181,  180,  179,  178,  177,  439,  439,  439,  439,
      155,  439,  150,  138,  137,  135,  439,  439,  118,  439,
      105,  439,  439,   46,   45,   89,   68,   68,  439,   46,
       45,  439,    3,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439
    } ;

static const flex_int16_t yy_chk[1061] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    5,   14,
      118,   18,   17,   15,   16,   21,  159,   25,  159,    2,
       14,   14,   14,   15,   16,   52,   17,   15,   19,   22,
       17,   21,  441,   18,    5,   17,  118,   16,   18,   25,

       18,   58,   65,   22,   24,   23,   14,   14,   14,   15,
       16,   19,   17,   15,   24,   23,   17,   21,   18,   23,
       17,   14,   16,   18,   25,   18,   29,   24,   26,   22,
       31,   58,   19,   27,   23,   91,   19,   52,   35,   47,
       24,   23,   47,   27,   41,   23,   41,   36,   65,   29,
       34,   26,   24,   31,   26,   29,   58,   26,   91,   23,
       35,   34,   34,   34,  195,   35,  195,   35,  429,   27,
       36,   98,   41,  163,   29,  426,   26,   49,   31,   26,
       29,   38,   26,   28,   37,   35,   50,   34,   34,   34,
       35,   54,   35,   28,   37,   36,   50,   28,   37,  163,

       64,   28,   53,   49,   38,   42,   28,   38,   55,  423,
       38,   54,   28,   37,   53,   98,   42,   42,   42,   28,
       37,   51,   50,   28,   37,  276,   64,   28,   49,   38,
       55,   28,   38,   42,   59,   38,   54,   28,   37,   51,
       53,   56,   42,   42,   42,   43,   59,   43,   43,   61,
       62,   64,   43,   43,   56,   55,   43,   42,   66,   67,
       69,   71,   62,   70,  420,   51,   72,  418,   76,   74,
       75,   79,   59,  276,   61,   67,   82,   61,   69,   77,
       56,   71,   74,   75,   78,   70,   87,   66,   62,   72,
       70,   76,   77,  197,  416,  197,   75,   82,   87,   61,

       84,   67,   61,   79,   69,   80,   71,   78,   74,   75,
       70,   84,   66,   83,   72,   70,   76,   85,   77,   80,
       88,   75,   82,   80,   87,   89,   95,   79,   78,   99,
       85,   97,   78,   96,   83,  103,  116,   84,  100,   99,
       95,  101,   88,   97,   96,   80,  106,   88,  100,   80,
       89,  101,  107,  103,  102,  108,   85,  104,  113,   83,
      114,  100,  107,  111,  116,   99,   95,   88,  102,   97,
       96,  104,   88,  111,  100,  106,  120,  101,  107,  103,
      112,  113,  119,  114,  108,  113,  100,  124,  107,  116,
      112,  115,  122,  125,  102,  123,  119,  104,  126,  111,

      106,  130,  120,  107,  129,  122,  113,  131,  114,  108,
      113,  132,  115,  123,  129,  133,  112,  142,  154,  126,
      141,  143,  119,  148,  140,  146,  187,  120,  130,  130,
      131,  122,  413,  124,  140,  152,  133,  115,  141,  123,
      129,  151,  168,  143,  126,  146,  154,  158,  412,  156,
      148,  151,  153,  130,  130,  131,  125,  161,  152,  157,
      140,  133,  153,  142,  141,  167,  153,  161,  143,  156,
      146,  154,  162,  158,  132,  148,  160,  151,  166,  157,
      161,  165,  168,  152,  172,  181,  167,  173,  153,  187,
      162,  174,  153,  161,  156,  165,  191,  183,  158,  176,

      411,  408,  160,  160,  157,  161,  186,  166,  189,  176,
      181,  167,  172,  173,  185,  193,  162,  191,  174,  405,
      183,  165,  176,  186,  185,  193,  178,  160,  160,  203,
      189,  198,  166,  198,  178,  176,  201,  172,  173,  199,
      202,  199,  191,  174,  178,  183,  178,  176,  204,  186,
      185,  193,  200,  203,  200,  189,  178,  178,  198,  205,
      209,  207,  210,  201,  211,  212,  215,  202,  224,  219,
      220,  228,  249,  204,  218,  212,  225,  231,  203,  219,
      220,  228,  211,  198,  218,  205,  242,  210,  201,  207,
      221,  219,  202,  215,  224,  237,  218,  218,  225,  243,

      221,  212,  221,  244,  209,  231,  242,  228,  211,  235,
      245,  235,  221,  221,  207,  236,  248,  236,  215,  238,
      237,  238,  239,  225,  239,  243,  246,  252,  244,  254,
      231,  242,  250,  245,  258,  249,  235,  252,  269,  254,
      250,  259,  236,  255,  248,  262,  238,  265,  267,  239,
      250,  268,  250,  255,  277,  259,  264,  270,  245,  258,
      271,  235,  250,  250,  269,  255,  255,  236,  272,  248,
      262,  238,  265,  267,  239,  273,  268,  246,  274,  264,
      281,  259,  270,  277,  280,  271,  272,  282,  286,  295,
      281,  297,  298,  300,  280,  404,  338,  282,  286,  283,

      273,  301,  281,  274,  264,  303,  280,  280,  277,  283,
      286,  283,  272,  302,  306,  295,  304,  297,  298,  300,
      308,  283,  283,  310,  306,  302,  311,  301,  318,  304,
      308,  303,  314,  310,  315,  322,  311,  323,  324,  325,
      332,  333,  304,  401,  340,  322,  329,  342,  311,  311,
      306,  302,  345,  318,  304,  349,  329,  352,  314,  338,
      315,  357,  323,  324,  325,  332,  333,  358,  329,  340,
      361,  322,  342,  367,  368,  400,  371,  345,  376,  414,
      377,  349,  352,  380,  399,  382,  385,  357,  386,  389,
      397,  395,  398,  358,  402,  361,  403,  424,  406,  367,

      368,  371,  409,  414,  376,  377,  410,  417,  419,  380,
      382,  385,  421,  425,  386,  389,  395,  422,  398,  402,
      427,  424,  403,  406,  428,  430,  431,  432,  409,  433,
      434,  410,  417,  436,  419,  437,  396,  394,  421,  425,
      393,  392,  422,  390,  388,  387,  427,  384,  383,  428,
      430,  381,  431,  432,  433,  434,  379,  378,  375,  436,
      437,  440,  440,  440,  442,  374,  442,  373,  372,  370,
      369,  366,  365,  364,  363,  362,  360,  359,  356,  355,
      351,  350,  348,  347,  346,  344,  343,  341,  337,  336,
      335,  334,  331,  330,  328,  327,  326,  319,  317,  316,

      313,  312,  309,  307,  305,  296,  294,  293,  291,  290,
      289,  288,  287,  285,  284,  278,  275,  266,  263,  261,
      260,  257,  256,  253,  251,  241,  240,  234,  233,  232,
      230,  229,  227,  226,  223,  222,  216,  213,  208,  206,
      196,  194,  192,  190,  188,  184,  182,  180,  179,  177,
      175,  171,  170,  169,  164,  155,  150,  149,  147,  145,
      144,  139,  138,  137,  136,  135,  128,  127,  121,  117,
      110,  109,  105,   94,   93,   90,   86,   81,   73,   63,
       60,   57,   48,   46,   44,   40,   39,   30,   20,   11,
        7,    3,  439,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer.l"
#line 2 "src/lexer.l"
    #include <stdio.h>
    #include <string.h> 
    #include "parser.tab.h"

    int DEBUG_LEX = 0;
    
    // Função auxiliar para converter números romanos para inteiros
    int romano_para_inteiro(const char *romano) {
        int valor = 0;
        while (*romano) {
            switch (*romano) {
                case 'M': valor += 1000; break;
                case 'D': valor += 500; break;
                case 'C':
                    if (*(romano + 1) == 'M') { valor += 900; romano++; }
                    else if (*(romano + 1) == 'D') { valor += 400; romano++; }
                    else valor += 100;
                    break;
                case 'L': valor += 50; break;
                case 'X':
                    if (*(romano + 1) == 'C') { valor += 90; romano++; }
                    else if (*(romano + 1) == 'L') { valor += 40; romano++; }
                    else valor += 10;
                    break;
                case 'V': valor += 5; break;
                case 'I':
                    if (*(romano + 1) == 'X') { valor += 9; romano++; }
                    else if (*(romano + 1) == 'V') { valor += 4; romano++; }
                    else valor += 1;
                    break;
            }
            romano++;
        }
        return valor;
    }
#line 857 "src/lex.yy.c"
#line 858 "src/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "src/lexer.l"

#line 1080 "src/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 440 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 993 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 39 "src/lexer.l"
{ /* comentário multilinha */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "src/lexer.l"
{
    char romano[16];
    sscanf(yytext, "ATO %15[^:]", romano);
    int numero = romano_para_inteiro(romano);
    if (DEBUG_LEX) printf("TOKEN: ATO (%s)\n", yytext);
    yylval.inteiro = numero;
    return ATO;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "src/lexer.l"
{
    char romano[16];
    sscanf(yytext, "CENA %15[^:]", romano);
    int numero = romano_para_inteiro(romano);
    if (DEBUG_LEX) printf("TOKEN: CENA (%s)\n", yytext);
    yylval.inteiro = numero;
    return CENA;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 58 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: E\n");
    yylval.texto = strdup(yytext);
    return E;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ARTIGO (%s)\n", yytext);
    yylval.texto = strdup(yytext);
    return ARTIGO;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 70 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ONDE_ESTAMOS\n");
    yylval.texto = strdup(yytext);
    return MOSTRAR_CENARIO;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 76 "src/lexer.l"
{
    // Adicione ao cenário
    if (DEBUG_LEX) printf("TOKEN: ADICIONAR_CENARIO\n");
    yylval.texto = strdup(yytext);
    return ADICIONAR_CENARIO;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 83 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SUBSTITUIR_CENARIO\n");
    yylval.texto = strdup(yytext);
    return SUBSTITUIR_CENARIO;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: POR\n");
    yylval.texto = strdup(yytext);
    return POR;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 95 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: NO_CENARIO\n");
    yylval.texto = strdup(yytext);
    return NO_CENARIO;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 101 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SE\n");
    yylval.texto = strdup(yytext);
    return SE;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SIM\n");
    yylval.texto = strdup(yytext);
    return SIM;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 113 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: NAO\n");
    yylval.texto = strdup(yytext);
    return NAO;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 121 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: EU\n");
    yylval.texto = strdup(yytext);
    return EU;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 127 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENTAO\n");
    yylval.texto = strdup(yytext);
    return ENTAO;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 133 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FOR\n");
    yylval.texto = strdup(yytext);
    return FOR;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 139 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENTRE\n");
    yylval.texto = strdup(yytext);
    return ENTRE;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 144 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MESMO\n");
    yylval.texto = strdup(yytext);
    return MESMO;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 149 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: TU\n");
    yylval.texto = strdup(yytext);
    return TU;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 154 "src/lexer.l"
{ // acentuação depois
    if (DEBUG_LEX) printf("TOKEN: É\n");
    yylval.texto = strdup(yytext);
    return EH;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 159 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SAEM\n");
    yylval.texto = strdup(yytext);
    return SAEM;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 165 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: TODOS\n");
    yylval.texto = strdup(yytext);
    return TODOS;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 171 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENTRAM\n");
    yylval.texto = strdup(yytext);
    return ENTRAM;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 177 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: VIRGULA\n");
    return VIRGULA;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 181 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SOMA\n");
    yylval.texto = strdup(yytext);
    return SOMAR;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 187 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: SUBTRAÇÃO\n");
    yylval.texto = strdup(yytext);
    return SUBTRAIR;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 193 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: DIVISÃO\n");
    yylval.texto = strdup(yytext);
    return DIVIDIR;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 199 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MULTIPLICAÇÃO\n");
    yylval.texto = strdup(yytext);
    return MULTIPLICAR;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 205 "src/lexer.l"
{
    // mais que
    if (DEBUG_LEX) printf("TOKEN: MAIOR\n");
    yylval.texto = strdup(yytext);
    return MAIOR;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 212 "src/lexer.l"
{
    // menos que
    if (DEBUG_LEX) printf("TOKEN: MENOR\n");
    yylval.texto = strdup(yytext);
    return MENOR;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 219 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MOSTRA_VALOR\n");
    yylval.texto = strdup(yytext);
    return MOSTRA_VALOR;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 224 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: LE_VALOR\n");
    yylval.texto = strdup(yytext);
    return LE_VALOR;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 230 "src/lexer.l"
{
    //igual que
    if (DEBUG_LEX) printf("TOKEN: IGUAL\n");
    yylval.texto = strdup(yytext);
    return IGUAL;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 237 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: NAO\n");
    yylval.texto = strdup(yytext);
    return NAO;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 243 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENQUANTO_COMECO\n");
    yylval.texto = strdup(yytext);
    return ENQUANTO_COMECO;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 249 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENQUANTO_FIM\n");
    yylval.texto = strdup(yytext);
    return ENQUANTO_FIM;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 255 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ENDIF\n");
    yylval.texto = strdup(yytext);
    return ENDIF;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 261 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FACA\n");
    yylval.texto = strdup(yytext);
    return FACA;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 267 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: DIVIDIR\n");
    yylval.texto = strdup(yytext);
    return DIVIDIR;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 273 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: MULTIPLICAR\n");
    yylval.texto = strdup(yytext);
    return MULTIPLICAR;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 279 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: INICIO\n");
    return INICIO;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 284 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FIM\n");
    return FIM;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 288 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: INTERROGACAO\n");
    return INTERROGACAO;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 293 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ABRE_COLCHETES\n");
    return ABRE_COLCHETES;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 298 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FECHA_COLCHETES\n");
    return FECHA_COLCHETES;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 303 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ABRE_PARENTESES\n");
    return ABRE_PARENTESES;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 308 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: FECHA_PARENTESES\n");
    return FECHA_PARENTESES;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 313 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: NUMERO (%s)\n", yytext);
    yylval.texto = strdup(yytext);
    return NUMERO;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 319 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ADJETIVO_POSITIVO (%s)\n", yytext);
    yylval.texto = strdup(yytext);
    return ADJETIVO_POSITIVO;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 324 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: ADJETIVO_NEGATIVO (%s)\n", yytext);
    yylval.texto = strdup(yytext);
    return ADJETIVO_NEGATIVO;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 329 "src/lexer.l"
{
    if (DEBUG_LEX) printf("TOKEN: TOKEN (%s)\n", yytext);
    yylval.texto = strdup(yytext);   // <-- AQUI ATRIBUI O VALOR
    return TOKEN;
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 336 "src/lexer.l"
{ /* ignora tudo o resto */ }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 338 "src/lexer.l"
ECHO;
	YY_BREAK
#line 1607 "src/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 440 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 440 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 439);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 338 "src/lexer.l"



int yywrap() {
    return 1;
}
